SOURCE_PRIVATBANK = 1
SOURCE_MONOBANK = 2
SOURCE_VKURSE = 3
SOURCE_NBU = 4
SOURCE_OTPBANK = 5
SOURCE_TASCOMBANK = 6

SOURCE_CHOICES = (
    (SOURCE_PRIVATBANK, 'PrivatBank'),
    (SOURCE_MONOBANK, 'MonoBank'),
    (SOURCE_VKURSE, 'Vkurse'),
    (SOURCE_NBU, 'NBU'),
    (SOURCE_OTPBANK, 'OTPBank'),
    (SOURCE_TASCOMBANK, 'TASComBank'),
)

CURRENCY_TYPE_USD = 1
CURRENCY_TYPE_EUR = 2

CURRENCY_TYPE_CHOICES = (
    (CURRENCY_TYPE_USD, 'USD'),
    (CURRENCY_TYPE_EUR, 'EUR')
)

RATE_TYPE_SALE = 1
RATE_TYPE_BUY = 2

RATE_TYPE_CHOICES = (
    (RATE_TYPE_SALE, 'Sale'),
    (RATE_TYPE_BUY, 'Buy')
)
