# Generated by Django 2.2.12 on 2020-06-07 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 16, 59, 46, 26419)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (3, 'Vkurse'), (4, 'NBU'), (5, 'OTPBank'), (6, 'TASComBank')]),
        ),
    ]
