# Generated by Django 2.2.12 on 2020-06-07 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20200607_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
